# Generated by Django 4.0.2 on 2022-02-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0002_conexion_router_switchmulticapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idServer', models.SlugField(max_length=15)),
                ('dirip', models.GenericIPAddressField()),
                ('storage_capacity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('unidad_storage', models.SlugField(max_length=3)),
                ('sistemaOP', models.CharField(max_length=30)),
                ('capacidadRAM', models.DecimalField(decimal_places=0, max_digits=2)),
                ('velocidad_trans', models.DecimalField(decimal_places=0, max_digits=3)),
                ('unidad_trans', models.SlugField(max_length=5)),
                ('capacidadCPU', models.DecimalField(decimal_places=0, max_digits=1)),
                ('color', models.SlugField(max_length=10)),
                ('tipo_conexion', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='conexion',
            old_name='idConnComp',
            new_name='idConn',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='idRoutComp',
            new_name='idRouter',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='idSWComp',
            new_name='idSW',
        ),
        migrations.RenameField(
            model_name='switchmulticapa',
            old_name='idSwMultComp',
            new_name='idSWM',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='tipo_comp',
        ),
        migrations.AddField(
            model_name='conexion',
            name='status',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comp', models.SlugField(max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tipo_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArbolPy.componente')),
            ],
        ),
    ]
