# Generated by Django 2.2.12 on 2022-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0005_auto_20220322_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='redscan',
            name='puertos_escaneo',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
