# Generated by Django 2.2.12 on 2022-03-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0006_redscan_puertos_escaneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='redscan',
            name='idEscaneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ArbolPy.RedScan'),
        ),
    ]
