# Generated by Django 2.2.12 on 2022-04-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0008_auto_20220326_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redscan',
            name='idEscaneo',
        ),
        migrations.AddField(
            model_name='redscan',
            name='MasRed',
            field=models.SlugField(default=-1, max_length=4),
            preserve_default=False,
        ),
    ]
