# Generated by Django 2.2.12 on 2022-05-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0009_auto_20220423_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRedIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graficaSegmento', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
