# Generated by Django 2.2.12 on 2022-05-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArbolPy', '0010_subredimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredimg',
            name='graficaSegmento',
            field=models.ImageField(upload_to=''),
        ),
    ]
